### ISSUE TITLE
Dot at end of python/fargate-flask/flask-docker-app/requirements.txt.?

### ISSUE THREAD

**Issue by dougtoppin** [pahud/cdk-samples#2]
Just checking to see if you meant to have a dot at the end of the following filename?

python/fargate-flask/flask-docker-app/requirements.txt.

**Comment by pahud** [comment]
Wow, thanks for your prompt feedback. https://github.com/pahud/cdk-samples/commit/9ddf72c21411a7c2796c96bc9470785b68b0b4a7

Let me know if you've found anything else wrong.

Thanks again!

**Comment by dougtoppin** [comment]
Will do, I forked and am adding a few changes such as x-ray and hoping to group log groups under a common prefix to make it easier to see them.

More to come.

Good example for cdk use. I am very pro Fargate and working on moving to using cdk.
Thanks for posting it.

**Comment by pahud** [comment]
@dougtoppin  Appreciated! I will share as many samples as I can.
